### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by astraw** [patdohere/FreeMoVR#1]
Hi, @patdohere et al.,

We have written software for free moving virtual reality for animals which we will release in the near future with an open source license. This release will coincide with a peer reviewed publication on our software. We would like to name our software "FreemoVR" but are afraid of name-clashes with this project.

Is this project still active? Do you see any potential problems with us also naming our software "FreemoVR"?

We would be happy to maintain a link to this project in case future searchers are confused.

Thanks in advance,
Andrew

**Comment by patdohere** [comment]
Nope I don't see any problems. This was a undergraduate project we worked on nothing important today.  Would love to read your paper once your done though.

**Comment by astraw** [comment]
Many thanks!
